/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Debtors" CASCADE;

CREATE TABLE "Debtors" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "debt" INTEGER NOT NULL);

